### ISSUE TITLE
When installing from the Live Environment Mode, language selection is not offered

### ISSUE THREAD

**Issue by cardpuncher** [shidel/FDI#12] opened 2020-06-04 14:18 UTC
This is rather a feature request: it would be nice if the user had the possibility to select his or her language after typing SETUP.BAT in the live environment mode as with the direct installation option from the startup menu.

**Comment by shidel** [comment] 2020-06-04 14:30
That is not a bug or error. The live environment assumes and sets the language to English (**set LANG=EN**). The installer sees the setting and skips asking. FDI does several things at startup to attempt to reduce asking questions. One of those is language detection. It will also skip asking when it manages to import that information from a pre-existing install.

If you change it before launching **SETUP.BAT**, like **set lang=tr**, then **SETUP** will switch fonts and run in Turkish.

To have it prompt, clear the language setting. **set LANG=** 

The **LiveCD** should actually have some simple program like maybe **SETLANG** that allows easy switching and codepage setup for multi-language users. I will probably create one that calls on **SETUP** to just do a quick language selection and exit without the install stuff.

**Comment by shidel** [comment] 2021-12-14 20:58
Forgot about this. But, done now... Will be in next release 1.3-Final. 
See [GitLab Issue](https://gitlab.com/FreeDOS/OS/builder/-/issues/3)

**Comment by cardpuncher** [comment] 2021-12-15 14:17
On 14.12.2021 23:58, shidel wrote:
> Forgot about this. But, done now... Will be in next release 1.3-Final.
> See GitLab Issue <https://gitlab.com/FreeDOS/OS/builder/-/issues/3>

Thank you! If there's an RC6, I'll give it a try for sure, otherwise in
1.3. I think we can happily close this report now :)

**Comment by shidel** [comment] 2021-12-15 16:24
I just made the installer ignore the **LANG** setting on the _LiveCD_. If it can manage to parse that information from a pre-existing installation, it will use that setting. 

Also, I didn't make a **SETLANG** to easily change languages... Yet... But, I did create a separate GitLab issue (feature request) for doing that sort of thing. So, at least this request can be closed. :-)

**Comment by shidel** [comment] 2022-02-01 12:08
fixed

**Closed as completed by shidel** 2022-02-01 12:08 UTC
Labels: enhancement
